version: "3.3"

services:
  db:
    container_name: postgres_superapp
    image: postgres:14
    volumes:
      - ../data_vuxko/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5440:5432"
  web:
    container_name: superapp
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8010:8000"
    env_file:
      - .env
    depends_on:
      - db

  webtest:
    container_name: superapptest
    build: .
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: "redis:latest"
    container_name: redis_superapp

  celery:
    container_name: superapp_celery
    build: .
    env_file:
      - .env
    volumes:
      - .:/code
    command: celery -A super_api.celery worker -B -l info
    depends_on:
      - redis


    
