# Generated by Django 4.1 on 2023-05-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_heroe_alignment_heroe_gender_heroe_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroe',
            name='id_external',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
